// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNJXNT2L0842e8YeK1Rdv2RUmyVx_jrws',
    appId: '1:9959449134:web:131f887318d79d6af5f5bf',
    messagingSenderId: '9959449134',
    projectId: 'vitalcare-7bc64',
    authDomain: 'vitalcare-7bc64.firebaseapp.com',
    storageBucket: 'vitalcare-7bc64.firebasestorage.app',
    measurementId: 'G-NVTY01HDQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDljPmYSX0OKIWXBKmiFr_p7L8aGrx8QGg',
    appId: '1:9959449134:android:0d83ecc98031615af5f5bf',
    messagingSenderId: '9959449134',
    projectId: 'vitalcare-7bc64',
    storageBucket: 'vitalcare-7bc64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo6kGIlhIFVTnWJg7H9QAC8rEI42pgM5E',
    appId: '1:9959449134:ios:92be3458bdfee613f5f5bf',
    messagingSenderId: '9959449134',
    projectId: 'vitalcare-7bc64',
    storageBucket: 'vitalcare-7bc64.firebasestorage.app',
    iosBundleId: 'com.example.vitalcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo6kGIlhIFVTnWJg7H9QAC8rEI42pgM5E',
    appId: '1:9959449134:ios:92be3458bdfee613f5f5bf',
    messagingSenderId: '9959449134',
    projectId: 'vitalcare-7bc64',
    storageBucket: 'vitalcare-7bc64.firebasestorage.app',
    iosBundleId: 'com.example.vitalcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNJXNT2L0842e8YeK1Rdv2RUmyVx_jrws',
    appId: '1:9959449134:web:2fc13207a20fa2cdf5f5bf',
    messagingSenderId: '9959449134',
    projectId: 'vitalcare-7bc64',
    authDomain: 'vitalcare-7bc64.firebaseapp.com',
    storageBucket: 'vitalcare-7bc64.firebasestorage.app',
    measurementId: 'G-J1VV9B277F',
  );
}
